from typing import Any, Optional, Protocol, runtime_checkable


@runtime_checkable
class TranslatorRunner(Protocol):
    def get(self, key: str, obj: Any = None, **kwargs: Any) -> str: ...

    def get_optional(self, key: str, obj: Any = None, **kwargs: Any) -> Optional[str]: ...

    def from_event(self, event: Any, **kwargs: Any) -> str: ...

    def __call__(self, obj: Any = None, **kwargs: Any) -> str: ...

    def __getattr__(self, item: str) -> "TranslatorRunner": ...


@runtime_checkable
class TranslatorHub(Protocol):
    def get_translator_by_locale(self, locale: str) -> TranslatorRunner: ...
