from typing import Optional, Protocol

from src.application.dto import MeteringTargetDto, SubscriptionPoolUsageDto, TrafficPoolDto


class TrafficPoolDao(Protocol):
    """Pools, and the per-subscription accounting windows opened against them."""

    async def get_all(self) -> list[TrafficPoolDto]: ...

    async def get_active(self) -> list[TrafficPoolDto]: ...

    async def get_by_id(self, pool_id: int) -> Optional[TrafficPoolDto]: ...

    async def create(self, pool: TrafficPoolDto) -> TrafficPoolDto: ...

    async def update(self, pool: TrafficPoolDto) -> Optional[TrafficPoolDto]: ...

    async def delete(self, pool_id: int) -> bool: ...

    async def count_plans_using(self, pool_id: int) -> int: ...

    # --- accounting windows -------------------------------------------------

    async def get_usage(
        self, subscription_id: int, pool_id: int
    ) -> Optional[SubscriptionPoolUsageDto]: ...

    async def list_usage(self, subscription_id: int) -> list[SubscriptionPoolUsageDto]: ...

    async def upsert_usage(self, usage: SubscriptionPoolUsageDto) -> SubscriptionPoolUsageDto: ...

    async def delete_usage(self, subscription_id: int, pool_ids: list[int]) -> None: ...

    async def carry_over_usage(self, from_subscription_id: int, to_subscription_id: int) -> int: ...

    async def get_metering_targets(self, pool_id: int) -> list[MeteringTargetDto]: ...
